version: 2.0
jobs:

  unittests:
    working_directory: ~/repo
    docker:
    - image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          pip install -r test-requirements.txt
    - run:
        name: Run unit tests
        command: |
          export PYTHONPATH=${PYTHONPATH}:$(pwd)
          export ENV=test
          pytest tests/*.py

  deploy:
    working_directory: ~/repo
      docker:
      - image: google/cloud-sdk:slim
      steps:
      - checkout
      - run:
          name: Create credentials file
          command: |
            mkdir credentials
            echo $CI_JSON_CREDENTIALS_PRODUCTION >> credentials/ci-production.json
      - run:
          name: Authenticate gcloud
          command: |
            gcloud auth activate-service-account --key-file credentials/ci-production.json

workflows:
  version: 2
  test-build-deploy:
    jobs:
    - unittests:
        filters:
          branches:
            ignore:
            - master

    - deploy:
        filters:
          branches:
            ignore:
            - master
